### ISSUE TITLE
Bad link to home page

### ISSUE THREAD

**Issue by ddssff** [ku-fpg/data-reify#5]
http://www.ittc.ku.edu/csdl/fpg/Tools/IOReification gives a 404 error

**Comment by andygill** [comment]
Thanks.

Where does this link come from? I can not find it on on the site.

**Comment by ddssff** [comment]
I see it on the hackage page: https://hackage.haskell.org/package/data-reify

It is copied there from the cabal file.

**Comment by RyanGlScott** [comment]
Oops, that's a link from KU FPG's old site. I've since updated it to the correct one (http://ku-fpg.github.io/software/data-reify/) on GitHub and Hackage.
